//! Export pipeline: HTML / PDF / EPUB.
//!
//! All exports are written to `<project>/exports/<basename>.<ext>` and the
//! resulting absolute path is returned to the caller.

use std::fs;
use std::io::{BufWriter, Cursor};
use std::path::{Path, PathBuf};

use pulldown_cmark::{html, Options, Parser};
use serde::{Deserialize, Serialize};

use crate::project::{self, Chapter, ProjectMeta};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExportResult {
    pub path: String,
    pub format: String,
    pub size_bytes: u64,
}

pub fn render_markdown_to_html(md: &str) -> String {
    let opts = Options::all();
    let parser = Parser::new_ext(md, opts);
    let mut body = String::new();
    html::push_html(&mut body, parser);
    body
}

pub fn collect_chapters(
    root: &Path,
    chapters: &[Chapter],
) -> Result<Vec<(Chapter, String)>, String> {
    let mut out = Vec::new();
    for ch in chapters {
        let md = project::read_chapter(root, &ch.filename)?;
        out.push((ch.clone(), md));
    }
    Ok(out)
}

fn ensure_exports_dir(root: &Path) -> Result<PathBuf, String> {
    let dir = project::exports_dir(root);
    fs::create_dir_all(&dir).map_err(|e| format!("mkdir exports: {}", e))?;
    Ok(dir)
}

/// Export the entire project as a single self-contained HTML file with
/// embedded CSS and a clickable table of contents.
pub fn export_html(root: &Path) -> Result<ExportResult, String> {
    let tree = project::open_project(root)?;
    let chapters = collect_chapters(root, &tree.chapters)?;
    let out_path = ensure_exports_dir(root)?.join(html_filename(&tree.meta.title));

    let mut toc = String::from("<nav class=\"toc\"><h2>Contents</h2><ol>");
    let mut body = String::new();
    for (i, (ch, md)) in chapters.iter().enumerate() {
        let id = format!("chapter-{}", i + 1);
        toc.push_str(&format!(
            "<li><a href=\"#{}\">{}</a></li>",
            id,
            html_escape(&ch.title)
        ));
        let html = render_markdown_to_html(md);
        let html = html.replacen("<h1>", &format!("<h1 id=\"{}\">", id), 1);
        body.push_str(&format!("<section class=\"chapter\">{}</section>", html));
    }
    toc.push_str("</ol></nav>");

    let css = include_str!("../assets/export.css");
    let html_doc = format!(
        r#"<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>{css}</style>
</head>
<body>
<header class="cover">
  <h1 class="book-title">{title}</h1>
  <p class="book-author">by {author}</p>
  <p class="book-version">v{version}</p>
</header>
{toc}
<main>
{body}
</main>
<footer>
  <p>Generated by BookForge on {date}</p>
</footer>
</body>
</html>"#,
        lang = html_escape(&tree.meta.language),
        title = html_escape(&tree.meta.title),
        author = html_escape(&tree.meta.author),
        version = html_escape(&tree.meta.version),
        css = css,
        toc = toc,
        body = body,
        date = chrono::Utc::now().format("%Y-%m-%d").to_string(),
    );

    fs::write(&out_path, html_doc).map_err(|e| format!("write html: {}", e))?;
    let size = fs::metadata(&out_path).map(|m| m.len()).unwrap_or(0);
    Ok(ExportResult {
        path: out_path.display().to_string(),
        format: "html".into(),
        size_bytes: size,
    })
}

/// Export the project as a PDF using `printpdf`. Renders chapters as styled
/// text laid out on A4 pages with simple word wrapping.
pub fn export_pdf(root: &Path) -> Result<ExportResult, String> {
    use printpdf::*;

    let tree = project::open_project(root)?;
    let chapters = collect_chapters(root, &tree.chapters)?;
    let out_path = ensure_exports_dir(root)?.join(pdf_filename(&tree.meta.title));

    let (doc, _page1_idx, _layer1_idx) =
        PdfDocument::new(tree.meta.title.clone(), Mm(210.0_f32), Mm(297.0_f32), "Layer 1");
    let font = doc
        .add_builtin_font(BuiltinFont::Helvetica)
        .map_err(|e| format!("font: {:?}", e))?;
    let font_bold = doc
        .add_builtin_font(BuiltinFont::HelveticaBold)
        .map_err(|e| format!("font bold: {:?}", e))?;
    let font_italic = doc
        .add_builtin_font(BuiltinFont::HelveticaOblique)
        .map_err(|e| format!("font italic: {:?}", e))?;

    let mut y: f32 = 270.0;
    let mut cur_page_idx;
    let mut cur_layer_idx;

    let (p_idx, l_idx) = doc.add_page(Mm(210.0_f32), Mm(297.0_f32), "Layer");
    cur_page_idx = p_idx;
    cur_layer_idx = l_idx;

    // Cover
    let title_lines = wrap_text(&tree.meta.title, 28);
    y = 220.0_f32;
    for line in &title_lines {
        let layer = doc.get_page(cur_page_idx).get_layer(cur_layer_idx);
        layer.use_text(line.clone(), 36.0_f32, Mm(20.0_f32), Mm(y), &font_bold);
        y -= 18.0_f32;
    }
    {
        let layer = doc.get_page(cur_page_idx).get_layer(cur_layer_idx);
        layer.use_text(
            format!("by {}", tree.meta.author),
            18.0_f32,
            Mm(20.0_f32),
            Mm(y - 10.0_f32),
            &font_italic,
        );
    }

    // Chapters
    for (ch, md) in &chapters {
        let (p_idx, l_idx) = doc.add_page(Mm(210.0_f32), Mm(297.0_f32), "Layer");
        cur_page_idx = p_idx;
        cur_layer_idx = l_idx;
        y = 270.0_f32;

        {
            let layer = doc.get_page(cur_page_idx).get_layer(cur_layer_idx);
            layer.use_text(
                ch.title.clone(),
                24.0_f32,
                Mm(20.0_f32),
                Mm(y),
                &font_bold,
            );
        }
        y -= 14.0_f32;

        for raw_line in md.lines() {
            let line = raw_line.trim();
            if line.is_empty() {
                y -= 6.0_f32;
                continue;
            }
            if line.starts_with('#') {
                if !line.starts_with("# ") {
                    let text = line.trim_start_matches('#').trim().to_string();
                    y -= 6.0_f32;
                    if y < 20.0_f32 {
                        let (p_idx, l_idx) = doc.add_page(Mm(210.0_f32), Mm(297.0_f32), "Layer");
                        cur_page_idx = p_idx;
                        cur_layer_idx = l_idx;
                        y = 280.0_f32;
                    }
                    let layer = doc.get_page(cur_page_idx).get_layer(cur_layer_idx);
                    layer.use_text(text, 14.0_f32, Mm(20.0_f32), Mm(y), &font_bold);
                    y -= 8.0_f32;
                }
                continue;
            }
            let plain = strip_markdown(line);
            for wrapped in wrap_text(&plain, 95) {
                if y < 20.0_f32 {
                    let (p_idx, l_idx) = doc.add_page(Mm(210.0_f32), Mm(297.0_f32), "Layer");
                    cur_page_idx = p_idx;
                    cur_layer_idx = l_idx;
                    y = 280.0_f32;
                }
                let layer = doc.get_page(cur_page_idx).get_layer(cur_layer_idx);
                layer.use_text(wrapped, 11.0_f32, Mm(20.0_f32), Mm(y), &font);
                y -= 5.5_f32;
            }
            y -= 2.0_f32;
        }
    }

    let file = fs::File::create(&out_path).map_err(|e| format!("create pdf: {}", e))?;
    let mut writer = BufWriter::new(file);
    doc.save(&mut writer)
        .map_err(|e| format!("save pdf: {:?}", e))?;
    drop(writer);

    let size = fs::metadata(&out_path).map(|m| m.len()).unwrap_or(0);
    Ok(ExportResult {
        path: out_path.display().to_string(),
        format: "pdf".into(),
        size_bytes: size,
    })
}

/// Export as EPUB using `epub-builder`.
pub fn export_epub(root: &Path) -> Result<ExportResult, String> {
    use epub_builder::{EpubBuilder, ZipLibrary};

    let tree = project::open_project(root)?;
    let chapters = collect_chapters(root, &tree.chapters)?;
    let out_path = ensure_exports_dir(root)?.join(epub_filename(&tree.meta.title));

    let zip = ZipLibrary::new().map_err(|e| format!("zip init: {:?}", e))?;
    let mut builder = EpubBuilder::new(zip).map_err(|e| format!("epub new: {:?}", e))?;
    builder
        .metadata("title", tree.meta.title.clone())
        .map_err(|e| format!("epub title: {:?}", e))?;
    builder
        .metadata("author", tree.meta.author.clone())
        .map_err(|e| format!("epub author: {:?}", e))?;
    builder
        .metadata("lang", tree.meta.language.clone())
        .map_err(|e| format!("epub lang: {:?}", e))?;
    if !tree.meta.description.is_empty() {
        builder
            .metadata("description", tree.meta.description.clone())
            .map_err(|e| format!("epub description: {:?}", e))?;
    }

    let css = "body { font-family: serif; line-height: 1.6; margin: 5%; }
               h1 { font-size: 1.6em; margin-top: 1em; }
               h2 { font-size: 1.3em; }
               p { text-indent: 1.5em; }";
    builder
        .stylesheet(css.as_bytes())
        .map_err(|e| format!("epub stylesheet: {:?}", e))?;

    for (i, (ch, md)) in chapters.iter().enumerate() {
        let html_body = render_markdown_to_html(md);
        let full_html = format!(
            "<html><head><title>{}</title></head><body>{}</body></html>",
            html_escape(&ch.title),
            html_body
        );
        let filename = format!("chapter_{:03}.xhtml", i + 1);
        let content =
            epub_builder::EpubContent::new(&filename, full_html.as_bytes()).title(ch.title.clone());
        builder
            .add_content(content)
            .map_err(|e| format!("epub add: {:?}", e))?;
    }

    let mut buf = Cursor::new(Vec::new());
    builder
        .generate(&mut buf)
        .map_err(|e| format!("epub generate: {:?}", e))?;
    let bytes = buf.into_inner();
    fs::write(&out_path, &bytes).map_err(|e| format!("write epub: {}", e))?;

    Ok(ExportResult {
        path: out_path.display().to_string(),
        format: "epub".into(),
        size_bytes: bytes.len() as u64,
    })
}

fn html_filename(title: &str) -> String {
    format!("{}.html", slugify(title))
}

fn pdf_filename(title: &str) -> String {
    format!("{}.pdf", slugify(title))
}

fn epub_filename(title: &str) -> String {
    format!("{}.epub", slugify(title))
}

pub fn slugify(s: &str) -> String {
    let lower: String = s.to_lowercase();
    let mut out = String::new();
    let mut prev_dash = false;
    for ch in lower.chars() {
        if ch.is_alphanumeric() {
            out.push(ch);
            prev_dash = false;
        } else if !prev_dash && (ch.is_whitespace() || ch == '-' || ch == '_') {
            out.push('-');
            prev_dash = true;
        }
    }
    out.trim_matches('-').to_string()
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn strip_markdown(s: &str) -> String {
    s.replace("**", "")
        .replace('*', "")
        .replace("__", "")
        .replace('_', "")
        .replace('`', "")
        .replace('[', "")
        .replace(']', "")
}

/// Naive word-wrap for PDF rendering.
fn wrap_text(s: &str, max_chars: usize) -> Vec<String> {
    let mut lines = Vec::new();
    for paragraph in s.split('\n') {
        let mut current = String::new();
        for word in paragraph.split_whitespace() {
            if current.is_empty() {
                current = word.to_string();
            } else if current.len() + 1 + word.len() <= max_chars {
                current.push(' ');
                current.push_str(word);
            } else {
                lines.push(std::mem::take(&mut current));
                current = word.to_string();
            }
        }
        if !current.is_empty() {
            lines.push(current);
        }
        if lines.is_empty() {
            lines.push(String::new());
        }
    }
    lines
}

#[allow(dead_code)]
pub fn _unused(_meta: &ProjectMeta) {}
